# Generated by Django 4.1.5 on 2023-05-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="first",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="last",
            new_name="last_name",
        ),
    ]
